### PR TITLE
Bug fixing

### PR DESCRIPTION
**Pull request by beccabunny**
The PR just merged broke the main page. This should fix it

### CODE REVIEW

**Comment by MCOfficer** [comment]
Out of curiosity, is there a way to test changes before PRing them? or is it just PR & pray?

**Comment by Fzzr** [comment]
@MCOfficer Only way I know is https://help.github.com/en/articles/setting-up-your-github-pages-site-locally-with-jekyll

**Comment by wispborne** [comment]
PR and pray.

If you clone the repo, you can set it up so you're hosting your own github pages, and for PRs, you can fork the contributor's repo. Rather work intensive. 

You can also clone the contributor's branch to your local box and run it locally. Also work intensive.

There's no CICD set up for PRs, which would be ideal.

**Comment by CodeDraken** [comment]
Yeah, you can set it up locally.

I just chose to PR and pray to save some time given the small size of the site and the option to rollback if necessary.

**Pull request merged**
