### PR TITLE
Changed mods to load from self-contained folders. Fixed table.

### PR DESCRIPTION
**Pull request by wispborne**
Removes hardcoding so that mods are loaded from a self-contained forder that contains all mod info. Also fixed how mods go into the table so they follow the same sequence as the mod listing.

Supports both local and linked images. 
Now allows multiple authors and tags as individual strings (rather than a single string).

### CODE REVIEW

**Comment by CodeDraken** [comment]
Looks like there's an error somewhere adding an extra space.
404 errors

**Comment by wispborne** [comment]
Nah, there's an underscore there. `_metadata.json`. 

Seems like the path is just not right when hosting from github.

https://github.com/davidwhitman/ES-Mod-Share/blob/gh-pages/mods/businessman/_metadata.json

It should work fine if you try it locally.

**Comment by CodeDraken** [comment]
Yeah it works locally. Seems to be just an error with the metadata file...
The mods.txt work and so do the other files.
https://davidwhitman.github.io/ES-Mod-Share/mods/businessman/banner.png

**Comment by wispborne** [comment]
Are you saying that it doesn't work when you actually try to host it as a github page? Do I need to change something?

**Comment by CodeDraken** [comment]
I viewed it here: https://davidwhitman.github.io/ES-Mod-Share/ and it doesn't work. Maybe it's just on that page. 
I'm going to get familiar with the code you wrote, and consider some things before adding it such as: potential problems with many GET requests on Github, file sizes, look into the Jekyll features, get feedback on it from community, etc...

**Comment by ItsNickBarry** [comment]
I fixed it [here](https://github.com/davidwhitman/ES-Mod-Share/pull/1), but if you're planning to use Jekyll, that won't work.  Removing the underscores from the file names would solve the problem.

**Comment by wispborne** [comment]
Ooo thank you. I didn't realize it was GitHub doing something unexpected. There's no reason to keep the underscores, I was just copying the starbound style. I'll try to remember tomorrow to change that. Saw your fork, looks good.

**Comment by wispborne** [comment]
I've removed the underscores (33eafb2) and, lo and behold, all is well now.

https://davidwhitman.github.io/ES-Mod-Share/

**Pull request merged**
