### PR TITLE
allow tag list to scroll independently of mod list

### PR DESCRIPTION
**Pull request by ItsNickBarry**
I've put the tag list into a fixed-position container with its own scroll bar.  Selecting a tag will now cause the mod list to scroll to the top.

The gh-pages site for my branch is [here](https://itsnickbarry.github.io/ES-Mod-Share).

### CODE REVIEW

**Comment by wispborne** [comment]
Thanks, this looks good. Same functionality as Google Keep, which is somewhat what I was modeling after.

The one thing I want to look into is removing the javascript resizing...the less styling is done with javascript, the better. I'll check it out later (need to boot into my linux dev env). 

And major thanks for the link to your site, saved me quite some time.

**Comment by ItsNickBarry** [comment]
You're right.  Based on examples I had looked at, I assumed CSS couldn't handle this alone.  It's working now without Javascript.

I had to remove the `#midWrap` div and the `.row` class from the `#modsDiv` for this to work.  I'm not sure what purpose they served.

**Comment by wispborne** [comment]
Those were fine to remove. `row` was part of bootstrap and was used in the old grid implementation that I replaced. Dunno about `#midWrap`.

**Comment by wispborne** [comment]
Merged, and thanks!

**Pull request merged**
